import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface PanattaMachineSeed {
  name: string;
  muscle: string;
  equipment: string;
  instructions: string;
  imageUrl: string | null;
  machineBrand: string;
  machineLine: string;
  machineCode: string;
  lengthCm: number | null;
  widthCm: number | null;
  heightCm: number | null;
  weightKg: number | null;
  maxLoadKg: number | null;
  isActive: boolean;
}

const panattaMachines: PanattaMachineSeed[] = [
  // ═══════════════════════════════════════
  // BENCHES
  // ═══════════════════════════════════════
  {
    name: "Seal Row Bench",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions:
      "Deite-se de bruços no banco elevado, segure a barra abaixo com pegada pronada, puxe até o banco contraindo os dorsais, e desça controladamente. Suportes de barra ajustáveis em 3 alturas. Plataforma traseira para fácil acesso ao banco.",
    imageUrl: "/machines/panatta/1fw518.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW518",
    lengthCm: 140,
    widthCm: 115,
    heightCm: 90,
    weightKg: 140,
    maxLoadKg: 400,
    isActive: false,
  },
  {
    name: "Curl Rack Bench",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Suporte versátil para exercícios de bíceps com barra reta ou curvada. Suportes de barra com ajuste de altura assistido a gás em 5 posições. Sistema de liberação por pedal. Opcional: barra e 6 suportes adicionais para anilhas.",
    imageUrl: "/machines/panatta/1fw509.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW509",
    lengthCm: 90,
    widthCm: 125,
    heightCm: 95,
    weightKg: 115,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Preacher Curl Bench",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Banco Scott para treino isolado de bíceps. Apoio de peito com ajuste de altura assistido a gás. Suportes rotativos para posicionar halteres ou barras conforme o treino. Suporte frontal inclinável para distanciar o usuário do carregamento de anilhas. Opcional: 4 suportes adicionais.",
    imageUrl: "/machines/panatta/1fw512.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW512",
    lengthCm: 145,
    widthCm: 135,
    heightCm: 85,
    weightKg: 100,
    maxLoadKg: 270,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — UPPER BODY
  // ═══════════════════════════════════════
  {
    name: "Super Vertical Multi Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions:
      "Reproduz a extensão de braços no supino com barra. Posição sentada com costas eretas. 2 barras multi-press específicas para tríceps e peitoral. Movimento semicircular com curva de carga fisiológica por sistema de alavancas. ROM ajustável. Smart switch para seleção rápida do tipo de barra. Alavanca para início fisiológico do movimento. Carga inicial: 15 kg.",
    imageUrl: "/machines/panatta/1fw045.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW045",
    lengthCm: 190,
    widthCm: 150,
    heightCm: 215,
    weightKg: 340,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Power Smith Dual System Upper",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions:
      "Foco no peitoral superior (feixes claviculares), deltoides e tríceps. Resistência de carga constante para estimulação hipertrófica contínua. Banco ajustável em 9 ângulos de 40° a 85° (supino inclinado até shoulder press). Assento com ajuste a gás. Trilho com ajuste horizontal em 28 posições. Contrapesos para reduzir peso vazio. Manípulos de empurrar com largura ajustável. Carga vazia: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw122.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW122",
    lengthCm: 164,
    widthCm: 190,
    heightCm: 205,
    weightKg: 320,
    maxLoadKg: 400,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — BICEPS
  // ═══════════════════════════════════════
  {
    name: "Alternate Preacher Curl Machine",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Replica o exercício spider curl para bíceps braquial e braquial anterior. Posição com ombro flexionado a 45° coloca o bíceps em encurtamento parcial, favorecendo o braquial. Apoio de peito ajustável com gás. Alavancas independentes para execução unilateral ou bilateral. Curva de carga fisiológica com CAM. Contrapeso para reduzir peso vazio. Pegadas articuladas rotativas. Manípulos em 2 ângulos: supinação e semi-supinação. Carga inicial: 2,5+2,5 kg.",
    imageUrl: "/machines/panatta/1fw054.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW054",
    lengthCm: 120,
    widthCm: 175,
    heightCm: 112,
    weightKg: 170,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Alternate Arm Curl 120",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Treino dos principais flexores do cotovelo. Posição com ombro flexionado a 120° coloca o bíceps braquial em encurtamento significativo, limitando sua força e permitindo que o braquial expresse seu potencial máximo. Assento ajustável com gás. Encosto ajustável em profundidade com gás. Alavancas independentes. Curva de carga fisiológica com CAM. Contrapeso. Pegadas articuladas rotativas em 2 ângulos. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw055.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW055",
    lengthCm: 125,
    widthCm: 190,
    heightCm: 140,
    weightKg: 200,
    maxLoadKg: 220,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — CORE
  // ═══════════════════════════════════════
  {
    name: "Total Core Crunch Machine",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions:
      "Treino completo de toda a musculatura abdominal. Sistema de seleção de movimento: flexão do tronco superior, flexão inferior com elevação de pelve e pernas, ou flexão simultânea completa. Assento rotativo para crunches com tronco rotacionado em 2 ângulos para cada lado (oblíquos internos e externos). Assento ajustável com gás em 5 posições. Sistema biomecânico multijoint. Curva de carga fisiológica com alavancas. Contrabalanceamento por mola. Apoio de ombros com sistema adaptativo a gás. Carga inicial: 10 kg.",
    imageUrl: "/machines/panatta/1fw065.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW065",
    lengthCm: 125,
    widthCm: 185,
    heightCm: 170,
    weightKg: 245,
    maxLoadKg: 135,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — LOWER BODY
  // ═══════════════════════════════════════
  {
    name: "3D Abductor",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions:
      "Reproduz simultaneamente abdução, extensão e rotação externa do quadril, trabalhando os feixes posteriores do glúteo médio. Comparada com abdutoras clássicas (apenas abdução no plano transversal), os componentes de extensão e rotação externa equilibram o estímulo entre tensor da fáscia lata e glúteo médio. Encosto ajustável em 3 inclinações para diferentes graus de flexão do quadril. Curva de carga fisiológica com alavancas. Contrabalanceamento por mola. Alavancas com sistema de entrada/saída assistido a gás.",
    imageUrl: "/machines/panatta/1fw199.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW199",
    lengthCm: 205,
    widthCm: 150,
    heightCm: 165,
    weightKg: 265,
    maxLoadKg: 270,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — LEG PRESS
  // ═══════════════════════════════════════
  {
    name: "Super Vertical Leg Press",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions:
      "Leg press vertical para treino completo de coxas. Encosto com inclinação ajustável. Plataforma de empurro ampla com inclinação ajustável. Sistema de partida fácil com alavanca de segurança. Limites de segurança ajustáveis em altura. Opcional: contrabalanceamento do peso vazio do carro, 8 suportes adicionais para anilhas, kit de balanceamento. Carga inicial: 90 kg.",
    imageUrl: "/machines/panatta/1fw093.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW093",
    lengthCm: 205,
    widthCm: 205,
    heightCm: 205,
    weightKg: 350,
    maxLoadKg: 800,
    isActive: false,
  },
  {
    name: "Super Leg Press 45° Dual System",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions:
      "Leg press 45° com plataformas independentes para execução bilateral, unilateral ou alternada. Encosto ajustável em 3 ângulos com acolchoamento de densidade variável. Sistema de deslizamento linear com carga constante em rodas de baixa fricção. Plataformas independentes de 40×60 cm cada. Dispositivo de travamento recíproco das plataformas. Tratamento antiderrapante. Alavancas de segurança independentes. Limites de segurança em 3 posições por lado. Alças laterais para fácil entrada/saída. Carga vazia: 50+50 kg.",
    imageUrl: "/machines/panatta/1fw090.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW090",
    lengthCm: 255,
    widthCm: 185,
    heightCm: 165,
    weightKg: 485,
    maxLoadKg: 900,
    isActive: false,
  },
  {
    name: "Super Leg Press 45°",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions:
      "Leg press 45° para treino completo de coxas. Encosto ajustável em 3 posições. Plataforma ampla em material antiderrapante. Sistema de partida fácil com alavanca de segurança. Limites de segurança ajustáveis em 3 posições. Alças laterais no carro para fácil entrada/saída. Acolchoamento de densidade variável com adaptação progressiva. Opcional: plataforma Super Grip, 6 suportes adicionais para anilhas. Carga inicial: 80 kg.",
    imageUrl: "/machines/panatta/1fw086.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW086",
    lengthCm: 255,
    widthCm: 185,
    heightCm: 165,
    weightKg: 410,
    maxLoadKg: 900,
    isActive: false,
  },
  {
    name: "Super Horizontal Leg Press Dual System",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions:
      "Leg press horizontal com plataformas independentes para execução mono ou bilateral. Reproduz o movimento de empurro sentado ao longo de superfície horizontal, eficaz para fortalecimento anterior/posterior de coxa e quadril. Assento e encosto ajustáveis em profundidade. Encosto em 3 ângulos. Curva de carga fisiológica com alavancas. Plataformas com sistema de segurança perimetral e tratamento antiderrapante. Dispositivo de travamento recíproco. Alça central para entrada/saída. Carga vazia: 15+15 kg.",
    imageUrl: "/machines/panatta/1fw100.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW100",
    lengthCm: 285,
    widthCm: 165,
    heightCm: 175,
    weightKg: 360,
    maxLoadKg: 450,
    isActive: false,
  },
  {
    name: "Super Leg Press Bridge",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions:
      "Leg press bridge para treino completo de membros inferiores. Assento-encosto ajustável em profundidade. Encosto ajustável em 7 ângulos. Acolchoamento de densidade variável com adaptação progressiva. Curva de carga fisiológica com alavancas. Plataforma ampla de 80×60 cm em material antiderrapante. Contrabalanceamento por mola para reduzir peso vazio. Movimento de partida fisiológico com alavanca de segurança. Alças laterais na plataforma. Opcional: plataforma Super Grip, 6 suportes adicionais. Carga inicial: 20 kg.",
    imageUrl: "/machines/panatta/1fw085.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW085",
    lengthCm: 275,
    widthCm: 165,
    heightCm: 165,
    weightKg: 380,
    maxLoadKg: 450,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — BICEPS (cont.)
  // ═══════════════════════════════════════
  {
    name: "Three Angles Biceps Machine",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Isolamento dos flexores do cotovelo (bíceps braquial e braquial). Superfície de trabalho ajustável em 3 inclinações, permitindo flexão do ombro até 90°, limitando progressivamente o bíceps braquial e colocando o braquial como executor principal. Assento ajustável com gás. Degraus laterais retráteis antiderrapantes. Alavancas independentes para execução bilateral ou unilateral. Curva de carga fisiológica com CAM. Contrapeso para reduzir peso vazio. Pegadas articuladas rotativas em 2 posições: supinação ou semi-supinação. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw451.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW451",
    lengthCm: 120,
    widthCm: 195,
    heightCm: 140,
    weightKg: 240,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Curling Machine",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Isolamento dos músculos bíceps e braquial. Assento ajustável com gás. Manípulo articulado com sistema adaptativo e pegada múltipla para pegada estreita ou larga. Curva de carga fisiológica com CAM conectada à alavanca. Opcional: 2 suportes adicionais para anilhas. Carga inicial: 10 kg.",
    imageUrl: "/machines/panatta/1fw351.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW351",
    lengthCm: 120,
    widthCm: 135,
    heightCm: 105,
    weightKg: 165,
    maxLoadKg: 110,
    isActive: false,
  },
  {
    name: "Alternate Curling Machine",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions:
      "Isolamento do braquial e bíceps braquial com execução alternada. Assento ajustável com gás. Alavancas independentes para execução bilateral ou unilateral. Curva de carga fisiológica com CAM conectada às alavancas. Pegadas rotativas e articuladas. Ajuste de ângulo em 2 posições: supinação ou semi-supinação. Opcional: 4 suportes adicionais para anilhas. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw251.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW251",
    lengthCm: 120,
    widthCm: 170,
    heightCm: 105,
    weightKg: 200,
    maxLoadKg: 220,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — TRICEPS
  // ═══════════════════════════════════════
  {
    name: "Triceps Machine",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions:
      "Isolamento do músculo tríceps. Assento ajustável com gás. Manípulo articulado com sistema adaptativo. Curva de carga fisiológica com CAM conectada à alavanca. Encosto bloqueável com regulação automática a gás. Contrapeso para zerar o peso vazio da alavanca. Opcional: 2 suportes adicionais para anilhas.",
    imageUrl: "/machines/panatta/1fw352.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW352",
    lengthCm: 165,
    widthCm: 135,
    heightCm: 145,
    weightKg: 175,
    maxLoadKg: 110,
    isActive: false,
  },
  {
    name: "Alternate Triceps Machine",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions:
      "Isolamento do tríceps com execução alternada. Assento ajustável com gás. Alavancas independentes para execução bilateral ou unilateral. Curva de carga fisiológica com CAM conectada às alavancas. Suporte traseiro para costas com regulação automática a gás. Pegadas articuladas. Alça central de apoio para estabilizar o corpo na execução unilateral. Opcional: 4 suportes adicionais para anilhas. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw252.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW252",
    lengthCm: 165,
    widthCm: 165,
    heightCm: 145,
    weightKg: 220,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Super French Press Machine",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions:
      "A primeira e original Super French Press Machine do mercado mundial de fitness. Treino específico de tríceps com ativação especial da cabeça longa. Assento com ajuste de altura a gás. Curva de carga fisiológica com sistema de alavancas. Manípulo rotativo com múltiplas pegadas para grip estreito ou largo. Contrabalanceamento por mola para zerar o peso vazio. Alavanca para início fisiológico do movimento. Opcional: apoio para pés antiderrapante, 6 suportes adicionais para anilhas.",
    imageUrl: "/machines/panatta/1fw053.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW053",
    lengthCm: 195,
    widthCm: 135,
    heightCm: 165,
    weightKg: 200,
    maxLoadKg: 220,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — SHOULDERS
  // ═══════════════════════════════════════
  {
    name: "Back Deltoids",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions:
      "Treino direcionado da cabeça posterior do deltoide. Assento com ajuste de altura a gás. Alavancas independentes para execução bilateral ou unilateral. Curva de carga fisiológica com sistema de alavancas. Contrabalanceamento por mola para zerar o peso vazio. Opcional: 6 suportes adicionais para anilhas.",
    imageUrl: "/machines/panatta/1fw026.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW026",
    lengthCm: 155,
    widthCm: 125,
    heightCm: 165,
    weightKg: 205,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Lateral Deltoids",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions:
      "Treino direcionado da cabeça lateral do deltoide. Assento com ajuste de altura a gás. Alavancas independentes para execução unilateral ou bilateral. Curva de carga fisiológica com sistema de alavancas. Contrabalanceamento por mola para zerar o peso vazio. Manípulos ajustáveis em comprimento para adaptar a cada usuário. Opcional: 6 suportes adicionais para anilhas. Carga vazia: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw027.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW027",
    lengthCm: 130,
    widthCm: 125,
    heightCm: 165,
    weightKg: 235,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Super Deltoid Press",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions:
      "Trajetória fisiológica para ombros, ideal para treino de deltoides e feixes claviculares do peitoral maior. Assento com ajuste de altura a gás. Encosto com ajuste horizontal a gás. Alavancas independentes para execução unilateral ou bilateral. Curva de carga fisiológica com sistema de alavancas. Múltiplas pegadas para grip neutro ou pronado. Alavanca para início fisiológico do movimento. Opcional: apoio para pés antiderrapante, 6 suportes adicionais para anilhas.",
    imageUrl: "/machines/panatta/1fw025.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW025",
    lengthCm: 205,
    widthCm: 150,
    heightCm: 165,
    weightKg: 255,
    maxLoadKg: 270,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — BACK (NEW)
  // ═══════════════════════════════════════
  {
    name: "Super High Row",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada alta com alavancas convergentes para dorsais e parte superior das costas. Assento com ajuste de altura a gás. Alavancas independentes para execução uni ou bilateral. Curva de carga fisiológica com sistema de alavancas. Múltiplas pegadas. Contrabalanceamento por mola.",
    imageUrl: "/machines/panatta/1fw003.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW003",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Low Row",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada baixa com alavancas convergentes para dorsais, romboides e trapézio inferior. Assento com ajuste de altura a gás. Alavancas independentes. Apoio de peito ajustável. Curva de carga fisiológica com sistema de alavancas. Contrabalanceamento por mola.",
    imageUrl: "/machines/panatta/1fw002.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW002",
    lengthCm: 155,
    widthCm: 150,
    heightCm: 190,
    weightKg: 210,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Dorsy Bar",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Barra dorsal para treino de dorsais com pegada variável. Assento com ajuste de altura a gás. Curva de carga fisiológica com sistema de alavancas. Contrabalanceamento por mola.",
    imageUrl: "/machines/panatta/1fw005.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW005",
    lengthCm: 185,
    widthCm: 125,
    heightCm: 140,
    weightKg: 150,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Front Dorsy Bar",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Barra dorsal frontal para treino de dorsais. Variação com puxada pela frente. Estrutura robusta com múltiplas pegadas.",
    imageUrl: "/machines/panatta/1fw105.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW105",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "T-Bar Row",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada T-Bar para dorsais e romboides. Apoio de peito para isolamento. Múltiplas pegadas para grip neutro e pronado. Suportes para anilhas.",
    imageUrl: "/machines/panatta/1fw007.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW007",
    lengthCm: 155,
    widthCm: 130,
    heightCm: 165,
    weightKg: 180,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Rowing",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada sentada com alavancas para dorsais. Apoio de peito ajustável. Alavancas independentes para execução uni ou bilateral. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw104.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW104",
    lengthCm: 180,
    widthCm: 150,
    heightCm: 165,
    weightKg: 240,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Rowing Circular",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada sentada com movimento circular para dorsais. Trajetória circular garante resistência constante em toda a amplitude. Apoio de peito. Alavancas independentes.",
    imageUrl: "/machines/panatta/1fw204.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW204",
    lengthCm: 215,
    widthCm: 150,
    heightCm: 165,
    weightKg: 240,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Power Row",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada com carga pesada para dorsais e trapézio. Plataforma para os pés. Alavancas independentes. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw102.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW102",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Lat Pulldown Circular",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Puxada alta com movimento circular para dorsais. Trajetória circular garante resistência constante. Múltiplas pegadas.",
    imageUrl: "/machines/panatta/1fw101.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW101",
    lengthCm: null,
    widthCm: 170,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Pullover Machine",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Pullover na máquina para dorsais e peitoral. Curva de carga fisiológica com sistema de alavancas. Amplitude de movimento ajustável.",
    imageUrl: "/machines/panatta/1fw039.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW039",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Shrug Machine",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Máquina para encolhimento de ombros (trapézio). Pegadas laterais ergonômicas. Curva de carga fisiológica com sistema de alavancas.",
    imageUrl: "/machines/panatta/1fw010.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW010",
    lengthCm: 180,
    widthCm: 150,
    heightCm: 165,
    weightKg: 220,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — CHEST (NEW)
  // ═══════════════════════════════════════
  {
    name: "Super Horizontal Bench Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Supino horizontal na máquina com alavancas convergentes. Alavancas independentes para execução uni ou bilateral. Assento com ajuste de altura a gás. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw037.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW037",
    lengthCm: 225,
    widthCm: 150,
    heightCm: 165,
    weightKg: 230,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Inclined Bench Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Supino inclinado na máquina com alavancas convergentes para peitoral superior. Alavancas independentes. Assento com ajuste. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw033.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW033",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Inclined Chest Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press inclinado para peitoral superior e deltoides anteriores. Alavancas independentes com curva de carga fisiológica. Assento ajustável.",
    imageUrl: "/machines/panatta/1fw035.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW035",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Declined Chest Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press declinado para porção inferior do peitoral. Alavancas independentes com curva de carga fisiológica. Assento ajustável.",
    imageUrl: "/machines/panatta/1fw041.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW041",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Vertical Chest Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press vertical para peitoral e tríceps. Movimento vertical com curva de carga fisiológica. Alavancas independentes.",
    imageUrl: "/machines/panatta/1fw036.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW036",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Horizontal Multi Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Multi press horizontal para peitoral e tríceps. Múltiplas barras para variações de grip. Curva de carga fisiológica com sistema de alavancas. Assento ajustável.",
    imageUrl: "/machines/panatta/1fw042.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW042",
    lengthCm: 230,
    widthCm: 150,
    heightCm: 165,
    weightKg: 300,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Upper Chest Flight Machine",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Crucifixo (fly) para porção superior do peitoral. Movimento de adução horizontal com inclinação. Alavancas independentes com curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw038.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW038",
    lengthCm: null,
    widthCm: 135,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Middle Chest Flight Machine",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Crucifixo (fly) para porção média do peitoral. Movimento de adução horizontal. Alavancas independentes com curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw043.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW043",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Lower Chest Flight Machine",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Crucifixo (fly) para porção inferior do peitoral. Movimento de adução horizontal com declinação. Alavancas independentes com curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw044.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW044",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Peck Back",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Peck deck e fly reverso combinados para peitoral e deltoides posteriores. Alavancas com curva de carga fisiológica. Assento ajustável.",
    imageUrl: "/machines/panatta/1fw117.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW117",
    lengthCm: 170,
    widthCm: 150,
    heightCm: 200,
    weightKg: 320,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Dips Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Máquina de mergulho (dips) para peitoral inferior e tríceps. Pegadas ergonômicas. Curva de carga fisiológica com sistema de alavancas.",
    imageUrl: "/machines/panatta/1fw140.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW140",
    lengthCm: 165,
    widthCm: 145,
    heightCm: 100,
    weightKg: 155,
    maxLoadKg: 310,
    isActive: false,
  },
  {
    name: "Dips Press Dual System",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Máquina de mergulho (dips) com sistema dual para peitoral inferior e tríceps. Alavancas independentes para execução uni ou bilateral. Pegadas ergonômicas.",
    imageUrl: "/machines/panatta/1fw040.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW040",
    lengthCm: 165,
    widthCm: 145,
    heightCm: 100,
    weightKg: 185,
    maxLoadKg: 310,
    isActive: false,
  },
  {
    name: "Power Smith Machine Dual System",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Smith machine com sistema dual para supino e shoulder press. Trilho com ajuste horizontal. Contrapesos para reduzir peso vazio. Banco ajustável em múltiplos ângulos.",
    imageUrl: "/machines/panatta/1fw121.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW121",
    lengthCm: 210,
    widthCm: 190,
    heightCm: 180,
    weightKg: 330,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — BICEPS (NEW)
  // ═══════════════════════════════════════
  {
    name: "Alternate Arm Curl -45",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Rosca alternada com ombro em extensão de -45°, colocando o bíceps braquial em alongamento máximo para ativação plena. Assento com ajuste a gás. Alavancas independentes. Curva de carga fisiológica com CAM. Contrapeso. Pegadas articuladas rotativas em 2 posições. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw056.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW056",
    lengthCm: 135,
    widthCm: 235,
    heightCm: 110,
    weightKg: 195,
    maxLoadKg: 220,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — TRICEPS (NEW)
  // ═══════════════════════════════════════
  {
    name: "Three Angles Triceps Machine",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions: "Isolamento do tríceps com superfície de trabalho ajustável em 3 inclinações. Permite diferentes setups de treino variando a posição do ombro. Alavancas independentes. Curva de carga fisiológica com CAM. Pegadas articuladas.",
    imageUrl: "/machines/panatta/1fw452.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW452",
    lengthCm: 125,
    widthCm: 185,
    heightCm: 180,
    weightKg: 290,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — SHOULDERS (NEW)
  // ═══════════════════════════════════════
  {
    name: "Viking Press and Calf",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Máquina combinada para desenvolvimento de ombros (viking press) e panturrilha. Permite treinar deltoides com pressing vertical e panturrilhas com elevação de calcanhares. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw029.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW029",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — LOWER BODY (NEW)
  // ═══════════════════════════════════════
  {
    name: "Alternate Leg Curling",
    muscle: "Hamstrings",
    equipment: "Panatta Machine",
    instructions: "Flexão de pernas alternada para isquiotibiais. Alavancas independentes para execução uni ou bilateral. Posição deitada. Curva de carga fisiológica com CAM.",
    imageUrl: "/machines/panatta/1fw082.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW082",
    lengthCm: 160,
    widthCm: 165,
    heightCm: 90,
    weightKg: 220,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Alternate Leg Extension",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Extensão de pernas alternada para quadríceps. Alavancas independentes para execução uni ou bilateral. Curva de carga fisiológica com CAM. Contrapeso para reduzir peso vazio. Carga inicial: 5+5 kg.",
    imageUrl: "/machines/panatta/1fw281.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW281",
    lengthCm: 155,
    widthCm: 195,
    heightCm: 144,
    weightKg: 235,
    maxLoadKg: 220,
    isActive: false,
  },
  {
    name: "Leg Extension",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Extensão de pernas para quadríceps. Curva de carga fisiológica com CAM. Assento ajustável. Encosto com adaptação progressiva.",
    imageUrl: "/machines/panatta/1fw181.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW181",
    lengthCm: 135,
    widthCm: 150,
    heightCm: 150,
    weightKg: 165,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Leg Curling",
    muscle: "Hamstrings",
    equipment: "Panatta Machine",
    instructions: "Flexão de pernas deitado para isquiotibiais. Curva de carga fisiológica com CAM. Apoio de quadril ajustável.",
    imageUrl: "/machines/panatta/1fw182.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW182",
    lengthCm: 160,
    widthCm: 150,
    heightCm: 90,
    weightKg: 160,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Seated Leg Curling",
    muscle: "Hamstrings",
    equipment: "Panatta Machine",
    instructions: "Flexão de pernas sentado para isquiotibiais. Curva de carga fisiológica com CAM. Assento ajustável. Apoio de coxa com regulação.",
    imageUrl: "/machines/panatta/1fw183.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW183",
    lengthCm: 135,
    widthCm: 150,
    heightCm: 150,
    weightKg: 180,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Kneeling Leg Curling",
    muscle: "Hamstrings",
    equipment: "Panatta Machine",
    instructions: "Flexão de pernas ajoelhado para isquiotibiais. Posição ajoelhada permite maior amplitude de movimento. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw094.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW094",
    lengthCm: null,
    widthCm: 170,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Belt Squat",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Agachamento com cinto para quadríceps, glúteos e isquiotibiais sem compressão espinal. Carga aplicada no quadril via cinto, eliminando carga axial na coluna. Plataforma com tratamento antiderrapante. Carga inicial: 20 kg.",
    imageUrl: "/machines/panatta/1fw095.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW095",
    lengthCm: 165,
    widthCm: 150,
    heightCm: 165,
    weightKg: 200,
    maxLoadKg: 270,
    isActive: false,
  },
  {
    name: "Super Hack Squat",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Hack squat para quadríceps, glúteos e isquiotibiais. Encosto ajustável. Plataforma ampla antiderrapante. Alavanca de segurança. Limites de segurança ajustáveis.",
    imageUrl: "/machines/panatta/1fw087.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW087",
    lengthCm: null,
    widthCm: 130,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Pendulum Squat",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Agachamento pendular para quadríceps, glúteos e isquiotibiais. Movimento pendular com curva de carga natural. Plataforma ampla. Encosto ajustável. Alavanca de segurança.",
    imageUrl: "/machines/panatta/1fw080.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW080",
    lengthCm: 210,
    widthCm: 150,
    heightCm: 190,
    weightKg: 350,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Power Squat",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Agachamento com carga pesada para quadríceps, glúteos e isquiotibiais. Apoios de ombro ajustáveis. Plataforma ampla. Alavanca de segurança.",
    imageUrl: "/machines/panatta/1fw084.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW084",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Squat Machine",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Máquina de agachamento para quadríceps, glúteos e isquiotibiais. Reproduz o movimento do agachamento com segurança. Apoios de ombro. Plataforma ampla.",
    imageUrl: "/machines/panatta/1fw091.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW091",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Super Calf Hack",
    muscle: "Calves",
    equipment: "Panatta Machine",
    instructions: "Máquina combinada de panturrilha e hack squat. Permite treinar panturrilha em pé e hack squat. Plataforma com tratamento antiderrapante. Apoios de ombro ajustáveis.",
    imageUrl: "/machines/panatta/1fw092.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW092",
    lengthCm: null,
    widthCm: 130,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Vertical Leg Press",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Leg press vertical para treino completo de coxas. Plataforma ampla. Alavanca de segurança. Limites de segurança ajustáveis.",
    imageUrl: "/machines/panatta/1fw193.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW193",
    lengthCm: 195,
    widthCm: 230,
    heightCm: 200,
    weightKg: 350,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Hip Thrust",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Máquina de hip thrust para glúteos e isquiotibiais. Reproduz o movimento de extensão de quadril em posição sentada/reclinada. Apoio de costas ajustável. Plataforma para os pés.",
    imageUrl: "/machines/panatta/1fw097.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW097",
    lengthCm: 200,
    widthCm: 150,
    heightCm: 140,
    weightKg: 180,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Power Runner",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Simulador de corrida com carga para quadríceps, glúteos e isquiotibiais. Movimento alternado de empurro. Plataformas independentes. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw098.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW098",
    lengthCm: 235,
    widthCm: 150,
    heightCm: 170,
    weightKg: 260,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Standing Abductor",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Abdução de quadril em pé para glúteo médio e abdutores. Posição em pé permite maior amplitude e ativação funcional. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw099.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW099",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Reverse Hyperextension",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Hiperextensão reversa para glúteos, isquiotibiais e eretores da espinha. Movimento de extensão do quadril com o tronco fixo. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw096.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW096",
    lengthCm: null,
    widthCm: 130,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Donkey Calf",
    muscle: "Calves",
    equipment: "Panatta Machine",
    instructions: "Panturrilha em posição donkey (inclinada) para gastrocnêmio e sóleo. Maior alongamento que na posição em pé. Apoio de quadril ajustável. Plataforma antiderrapante. Carga inicial: 70 kg.",
    imageUrl: "/machines/panatta/1fw089.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW089",
    lengthCm: 185,
    widthCm: 130,
    heightCm: 170,
    weightKg: 200,
    maxLoadKg: 310,
    isActive: false,
  },
  {
    name: "Super Seated Calf",
    muscle: "Calves",
    equipment: "Panatta Machine",
    instructions: "Panturrilha sentado para sóleo. Apoio de joelho ajustável. Plataforma antiderrapante. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fw088.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW088",
    lengthCm: 160,
    widthCm: 130,
    heightCm: 165,
    weightKg: 150,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════
  // PLATE LOADED — RACKS & PLATFORMS
  // ═══════════════════════════════════════
  {
    name: "Military Bench",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Banco militar para desenvolvimento de ombros com barra. Suportes ajustáveis em altura. Encosto ajustável. Apoio para os pés.",
    imageUrl: "/machines/panatta/1fw533.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW533",
    lengthCm: 130,
    widthCm: 160,
    heightCm: 185,
    weightKg: 225,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Power Rack",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Power rack olímpico para agachamento, supino e exercícios com barra. Barras de segurança ajustáveis. Suportes para barra em múltiplas alturas. Estrutura reforçada.",
    imageUrl: "/machines/panatta/1fw531.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW531",
    lengthCm: null,
    widthCm: 145,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Half Rack",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Half rack olímpico para agachamento, supino e exercícios com barra. Barras de segurança ajustáveis. Suportes para barra. Mais compacto que o power rack completo.",
    imageUrl: "/machines/panatta/1fw534.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW534",
    lengthCm: null,
    widthCm: 145,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Smith Machine Counterbalanced",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Smith machine olímpica com contrapeso para reduzir peso vazio da barra. Trilho linear para movimento guiado. Barras de segurança. Suportes ajustáveis.",
    imageUrl: "/machines/panatta/1fw520.png",
    machineBrand: "Panatta",
    machineLine: "FreeWeight Special",
    machineCode: "1FW520",
    lengthCm: null,
    widthCm: 145,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — BACK
  // ═══════════════════════════════════════════════════
  {
    name: "Lat Pulldown",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Puxada alta seletorizada para dorsais. Barra com múltiplas pegadas. Apoio de coxa ajustável. Pilha de pesos padrão 50 kg (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe001.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE001",
    lengthCm: 140,
    widthCm: 120,
    heightCm: 240,
    weightKg: 195,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Lat Pulldown Circular",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Puxada alta com movimento circular para dorsais. Resistência constante em toda a amplitude. Pilha de pesos padrão.",
    imageUrl: "/machines/panatta/1fe002.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE002",
    lengthCm: 95,
    widthCm: 150,
    heightCm: 220,
    weightKg: 265,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Pulley Row",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada baixa seletorizada com polia para dorsais. Apoio de peito/pés. Barra com múltiplas pegadas.",
    imageUrl: "/machines/panatta/1fe003.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE003",
    lengthCm: 175,
    widthCm: 100,
    heightCm: 225,
    weightKg: 215,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Pulley Row Double Stack",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada baixa com dupla pilha de pesos para cargas mais altas. Apoio de peito/pés. Barra com múltiplas pegadas.",
    imageUrl: "/machines/panatta/1fe103.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE103",
    lengthCm: 210,
    widthCm: 110,
    heightCm: 215,
    weightKg: 260,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Rowing Machine Circular",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada sentada com movimento circular para dorsais. Resistência constante. Apoio de peito.",
    imageUrl: "/machines/panatta/1fe004a.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE004A",
    lengthCm: 160,
    widthCm: 130,
    heightCm: 185,
    weightKg: 270,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Lat Pulldown Convergent",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Puxada alta convergente para dorsais. Alavancas independentes com movimento convergente. Apoio de coxa.",
    imageUrl: "/machines/panatta/1fe007.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE007",
    lengthCm: 170,
    widthCm: 125,
    heightCm: 210,
    weightKg: 260,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "High Row Convergent",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Remada alta convergente para dorsais e trapézio. Alavancas independentes com movimento convergente. Apoio de peito.",
    imageUrl: "/machines/panatta/1fe006.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE006",
    lengthCm: 160,
    widthCm: 115,
    heightCm: 210,
    weightKg: 265,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Lat Pulldown Double Stack",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Puxada alta com dupla pilha de pesos para cargas mais altas. Barra com múltiplas pegadas. Apoio de coxa.",
    imageUrl: "/machines/panatta/1fe101.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE101",
    lengthCm: 115,
    widthCm: 130,
    heightCm: 250,
    weightKg: 250,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Lower Back",
    muscle: "Lower Back",
    equipment: "Panatta Machine",
    instructions: "Extensão lombar seletorizada para eretores da espinha e fáscia toracolombar. Apoio de quadril ajustável. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe005.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE005",
    lengthCm: 150,
    widthCm: 140,
    heightCm: 160,
    weightKg: 185,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — CHEST
  // ═══════════════════════════════════════════════════
  {
    name: "Vertical Chest Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press vertical seletorizado para peitoral. Alavancas independentes. Assento ajustável. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe036.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE036",
    lengthCm: 120,
    widthCm: 150,
    heightCm: 160,
    weightKg: 230,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Vertical Chest Press Circular",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press vertical com movimento circular para peitoral. Resistência constante em toda a amplitude.",
    imageUrl: "/machines/panatta/1fe033.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE033",
    lengthCm: 125,
    widthCm: 145,
    heightCm: 185,
    weightKg: 270,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Inclined Chest Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press inclinado seletorizado para peitoral superior. Alavancas independentes. Assento ajustável.",
    imageUrl: "/machines/panatta/1fe037.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE037",
    lengthCm: 145,
    widthCm: 160,
    heightCm: 190,
    weightKg: 210,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Inclined Chest Press Circular",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Chest press inclinado com movimento circular para peitoral superior. Resistência constante.",
    imageUrl: "/machines/panatta/1fe034.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE034",
    lengthCm: 135,
    widthCm: 145,
    heightCm: 185,
    weightKg: 265,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Pectoral Machine",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Peck deck seletorizado para peitoral. Movimento de adução horizontal. Braços ajustáveis. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe035.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE035",
    lengthCm: 130,
    widthCm: 145,
    heightCm: 160,
    weightKg: 230,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Pullover Machine",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Pullover seletorizado para dorsais e peitoral. Curva de carga fisiológica. Amplitude ajustável. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe039.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE039",
    lengthCm: 150,
    widthCm: 140,
    heightCm: 160,
    weightKg: 235,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Peck Back",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Peck deck e fly reverso combinados seletorizados. Permite treinar peitoral e deltoides posteriores na mesma máquina.",
    imageUrl: "/machines/panatta/1fe117.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE117",
    lengthCm: 130,
    widthCm: 140,
    heightCm: 195,
    weightKg: 165,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Multipurpose Press",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Press multiuso seletorizado para peitoral e ombros. Alavancas ajustáveis para diferentes ângulos de pressão. Assento ajustável.",
    imageUrl: "/machines/panatta/1fe118a.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE118A",
    lengthCm: 175,
    widthCm: 150,
    heightCm: 160,
    weightKg: 305,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — SHOULDERS
  // ═══════════════════════════════════════════════════
  {
    name: "Deltoid Press",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Desenvolvimento de ombros seletorizado para deltoides. Alavancas independentes. Assento ajustável. Pilha padrão 80 kg (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe025.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE025",
    lengthCm: 170,
    widthCm: 160,
    heightCm: 160,
    weightKg: 210,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Deltoid Press Circular",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Desenvolvimento de ombros com movimento circular para deltoides. Resistência constante. Pilha padrão 100 kg (opcional 120 kg).",
    imageUrl: "/machines/panatta/1fe024.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE024",
    lengthCm: 140,
    widthCm: 145,
    heightCm: 185,
    weightKg: 275,
    maxLoadKg: 120,
    isActive: false,
  },
  {
    name: "Rotary Cuff",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Máquina para rotação do manguito rotador. Treino de rotação interna e externa do ombro. Assento ajustável.",
    imageUrl: "/machines/panatta/1fe027.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE027",
    lengthCm: 105,
    widthCm: 150,
    heightCm: 160,
    weightKg: 190,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Standing Multi Flight",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Elevação lateral em pé seletorizada para deltoides, peitoral e dorsais. Múltiplas posições para diferentes movimentos de voo.",
    imageUrl: "/machines/panatta/1fe028.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE028",
    lengthCm: 145,
    widthCm: 80,
    heightCm: 195,
    weightKg: 280,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — BICEPS
  // ═══════════════════════════════════════════════════
  {
    name: "Alternate Arm Curl",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Rosca alternada seletorizada para bíceps. Alavancas independentes. Pegadas articuladas. Pilha padrão 50 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe056.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE056",
    lengthCm: 85,
    widthCm: 150,
    heightCm: 160,
    weightKg: 180,
    maxLoadKg: 80,
    isActive: false,
  },
  {
    name: "Alternate Arm Curl -45",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Rosca alternada com ombro em extensão de -45° seletorizada. Bíceps em alongamento máximo. Alavancas independentes. Pilha padrão 60 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe456.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE456",
    lengthCm: 130,
    widthCm: 150,
    heightCm: 160,
    weightKg: 210,
    maxLoadKg: 80,
    isActive: false,
  },
  {
    name: "Alternate Supinating Biceps",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Rosca alternada com supinação seletorizada para bíceps. Movimento de rotação do antebraço durante a flexão. Alavancas independentes. Pilha padrão 50 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe556.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE556",
    lengthCm: 85,
    widthCm: 160,
    heightCm: 160,
    weightKg: 265,
    maxLoadKg: 80,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — TRICEPS
  // ═══════════════════════════════════════════════════
  {
    name: "Alternate Arm Extension",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions: "Extensão de braço alternada seletorizada para tríceps. Alavancas independentes. Pegadas articuladas. Pilha padrão 50 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe057.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE057",
    lengthCm: 85,
    widthCm: 150,
    heightCm: 160,
    weightKg: 190,
    maxLoadKg: 80,
    isActive: false,
  },
  {
    name: "Alternate Arm Extension 90",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions: "Extensão de braço alternada a 90° seletorizada para tríceps. Ombro a 90° para maior ativação da cabeça longa. Alavancas independentes. Pilha padrão 60 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe357.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE357",
    lengthCm: 90,
    widthCm: 155,
    heightCm: 160,
    weightKg: 220,
    maxLoadKg: 80,
    isActive: false,
  },
  {
    name: "Alternate Pronating Triceps",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions: "Extensão de tríceps com pronação alternada seletorizada. Movimento de rotação do antebraço durante a extensão. Alavancas independentes. Pilha padrão 50 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe557.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE557",
    lengthCm: 105,
    widthCm: 160,
    heightCm: 160,
    weightKg: 245,
    maxLoadKg: 80,
    isActive: false,
  },
  {
    name: "French Press Machine (Fit Evo)",
    muscle: "Triceps",
    equipment: "Panatta Machine",
    instructions: "French press seletorizado para tríceps com ativação da cabeça longa. Assento ajustável. Curva de carga fisiológica.",
    imageUrl: "/machines/panatta/1fe153.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE153",
    lengthCm: 130,
    widthCm: 190,
    heightCm: 160,
    weightKg: 250,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — BICEPS+TRICEPS COMBO
  // ═══════════════════════════════════════════════════
  {
    name: "Standing Total Arms",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Máquina combinada para bíceps e tríceps em pé. Permite treinar rosca e extensão na mesma estação. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe055a.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE055A",
    lengthCm: 115,
    widthCm: 125,
    heightCm: 180,
    weightKg: 260,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Alternate Standing Total Arms",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Máquina combinada alternada para bíceps e tríceps em pé. Alavancas independentes. Permite execução uni ou bilateral. Pilhas duplas 50+50 kg (opcional 80+80 kg).",
    imageUrl: "/machines/panatta/1fe155.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE155",
    lengthCm: 140,
    widthCm: 175,
    heightCm: 180,
    weightKg: 460,
    maxLoadKg: 160,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — LOWER BODY
  // ═══════════════════════════════════════════════════
  {
    name: "Horizontal Leg Press",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Leg press horizontal seletorizado para quadríceps, glúteos e isquiotibiais. Encosto ajustável. Plataforma ampla. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe085.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE085",
    lengthCm: 220,
    widthCm: 120,
    heightCm: 185,
    weightKg: 355,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Adductor Machine",
    muscle: "Adductors",
    equipment: "Panatta Machine",
    instructions: "Adutora seletorizada para adutores. Amplitude ajustável. Assento ajustável. Pilha padrão 50 kg (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe087.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE087",
    lengthCm: 185,
    widthCm: 70,
    heightCm: 160,
    weightKg: 185,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Adductor/Abductor Machine",
    muscle: "Adductors",
    equipment: "Panatta Machine",
    instructions: "Adutora/abdutora combinada seletorizada. Troca entre adução e abdução. Amplitude ajustável. Pilha padrão 50 kg (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe093.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE093",
    lengthCm: 185,
    widthCm: 70,
    heightCm: 160,
    weightKg: 200,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Standing Abductor Machine",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Abdutora em pé seletorizada para glúteo médio e abdutores. Posição em pé para maior ativação funcional.",
    imageUrl: "/machines/panatta/1fe096.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE096",
    lengthCm: 160,
    widthCm: 80,
    heightCm: 160,
    weightKg: 230,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Gluteus Machine",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Máquina de glúteos seletorizada para extensão de quadril. Alavanca com apoio de pé. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe088.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE088",
    lengthCm: 150,
    widthCm: 110,
    heightCm: 160,
    weightKg: 215,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Master Gluteus Plus",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Máquina avançada de glúteos seletorizada. Combinação de extensão e abdução de quadril para ativação completa dos glúteos.",
    imageUrl: "/machines/panatta/1fe094a.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE094A",
    lengthCm: 205,
    widthCm: 115,
    heightCm: 160,
    weightKg: 335,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Multi Hip",
    muscle: "Glutes",
    equipment: "Panatta Machine",
    instructions: "Multi hip seletorizado para abdutores, adutores e glúteos. Permite flexão, extensão, abdução e adução do quadril. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe090.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE090",
    lengthCm: 135,
    widthCm: 100,
    heightCm: 160,
    weightKg: 190,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Calf Machine",
    muscle: "Calves",
    equipment: "Panatta Machine",
    instructions: "Panturrilha em pé seletorizada para gastrocnêmio e sóleo. Apoios de ombro ajustáveis. Plataforma antiderrapante. Pilha padrão 100 kg (opcional 120 kg).",
    imageUrl: "/machines/panatta/1fe089.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE089",
    lengthCm: 95,
    widthCm: 100,
    heightCm: 190,
    weightKg: 210,
    maxLoadKg: 120,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — SELECTORIZED — CORE
  // ═══════════════════════════════════════════════════
  {
    name: "Upper Abdominal",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Abdominal superior seletorizado para reto abdominal. Apoio de ombros ajustável. Curva de carga fisiológica. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe065.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE065",
    lengthCm: 160,
    widthCm: 140,
    heightCm: 160,
    weightKg: 180,
    maxLoadKg: null,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — MULTIFUNCTIONAL / CABLES
  // ═══════════════════════════════════════════════════
  {
    name: "Cable Crossover",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Crossover de cabos seletorizado para treino funcional de todo o corpo. Polias ajustáveis em altura. Múltiplas pegadas. Pilha padrão 50 kg por lado (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe111.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE111",
    lengthCm: 370,
    widthCm: 100,
    heightCm: 220,
    weightKg: 245,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Adjustable Cable Crossover",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Crossover de cabos com polias ajustáveis em altura para treino funcional. Múltiplas posições de polia. Pilha padrão 50 kg por lado (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe125.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE125",
    lengthCm: 390,
    widthCm: 95,
    heightCm: 230,
    weightKg: 390,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "High Low Pulley",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Polia alta e baixa seletorizada para exercícios variados. Polia superior e inferior. Pilha de pesos.",
    imageUrl: "/machines/panatta/1fe114b.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE114B",
    lengthCm: 90,
    widthCm: 95,
    heightCm: 230,
    weightKg: 150,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "4-Station Multi Gym",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Estação multifuncional de 4 estações para treino completo do corpo. Pilha padrão 50 kg por estação (opcional 100 kg).",
    imageUrl: "/machines/panatta/1fe112.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE112",
    lengthCm: 140,
    widthCm: 130,
    heightCm: 230,
    weightKg: 380,
    maxLoadKg: 100,
    isActive: false,
  },
  {
    name: "Jungle Machine",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Jungle machine multifuncional para treino funcional com cabos. Múltiplas estações e polias. Permite exercícios variados para todo o corpo.",
    imageUrl: "/machines/panatta/1fe115.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE115",
    lengthCm: 175,
    widthCm: 240,
    heightCm: 240,
    weightKg: 525,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Jungle Machine HLP",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Jungle machine HLP (High Low Pulley) multifuncional. Polias altas e baixas para exercícios variados. Múltiplas estações.",
    imageUrl: "/machines/panatta/1fe120.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE120",
    lengthCm: 175,
    widthCm: 240,
    heightCm: 240,
    weightKg: 525,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Chin and Dip Counterbalanced",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Barra fixa e paralelas com contrapeso assistido para chin-ups e dips. Plataforma com contrapeso ajustável para assistência. Pilha padrão 50 kg (opcional 80 kg).",
    imageUrl: "/machines/panatta/1fe121.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE121",
    lengthCm: 165,
    widthCm: 110,
    heightCm: 240,
    weightKg: 300,
    maxLoadKg: 80,
    isActive: false,
  },

  // ═══════════════════════════════════════════════════
  // FIT EVO — BENCHES
  // ═══════════════════════════════════════════════════
  {
    name: "Flat Bench (Fit Evo)",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Banco reto para supino e exercícios com halteres. Estofamento de alta densidade.",
    imageUrl: "/machines/panatta/1fe202.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE202",
    lengthCm: 145,
    widthCm: 75,
    heightCm: 50,
    weightKg: 35,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Fully Adjustable Bench",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Banco totalmente ajustável para múltiplos ângulos. De plano a 90°. Assento com ajuste de inclinação.",
    imageUrl: "/machines/panatta/1fe201.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE201",
    lengthCm: null,
    widthCm: 75,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Flat Bench",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Banco olímpico reto para supino com barra. Suportes ajustáveis. Estofamento de alta densidade.",
    imageUrl: "/machines/panatta/1fe203.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE203",
    lengthCm: null,
    widthCm: 155,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Inclined Bench",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Banco olímpico inclinado para supino inclinado com barra. Suportes ajustáveis. Estofamento de alta densidade.",
    imageUrl: "/machines/panatta/1fe205.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE205",
    lengthCm: 180,
    widthCm: 155,
    heightCm: 165,
    weightKg: 140,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Declined Bench",
    muscle: "Chest",
    equipment: "Panatta Machine",
    instructions: "Banco olímpico declinado para supino declinado com barra. Suportes ajustáveis. Apoio de pernas.",
    imageUrl: "/machines/panatta/1fe206.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE206",
    lengthCm: null,
    widthCm: 155,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Olympic Shoulder Bench",
    muscle: "Shoulders",
    equipment: "Panatta Machine",
    instructions: "Banco olímpico para desenvolvimento de ombros com barra. Suportes ajustáveis. Encosto ajustável.",
    imageUrl: "/machines/panatta/1fe207.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE207",
    lengthCm: null,
    widthCm: 155,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Multipurpose Seated Bench",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Banco multiuso sentado para exercícios variados com halteres. Encosto ajustável em múltiplos ângulos.",
    imageUrl: "/machines/panatta/1fe204.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE204",
    lengthCm: null,
    widthCm: 75,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Seated Curl Bench",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Banco Scott sentado para rosca com halteres. Apoio de braço ajustável.",
    imageUrl: "/machines/panatta/1fe208.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE208",
    lengthCm: null,
    widthCm: 85,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Curl Rack",
    muscle: "Biceps",
    equipment: "Panatta Machine",
    instructions: "Suporte para rosca com barra. Suportes ajustáveis em altura.",
    imageUrl: "/machines/panatta/1fe209.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE209",
    lengthCm: 85,
    widthCm: 110,
    heightCm: 100,
    weightKg: 40,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Chin and Dip",
    muscle: "Back",
    equipment: "Panatta Machine",
    instructions: "Barra fixa e paralelas para chin-ups, pull-ups e dips. Múltiplas pegadas. Apoio lombar.",
    imageUrl: "/machines/panatta/1fe211.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE211",
    lengthCm: 125,
    widthCm: 135,
    heightCm: 265,
    weightKg: 135,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Adjustable Back Extension",
    muscle: "Lower Back",
    equipment: "Panatta Machine",
    instructions: "Hiperextensão lombar ajustável para eretores da espinha e fáscia toracolombar. Apoio de quadril ajustável.",
    imageUrl: "/machines/panatta/1fe200.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE200",
    lengthCm: 145,
    widthCm: 95,
    heightCm: 130,
    weightKg: 75,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Iperextension Bench",
    muscle: "Lower Back",
    equipment: "Panatta Machine",
    instructions: "Banco de hiperextensão horizontal para eretores da espinha e fáscia toracolombar.",
    imageUrl: "/machines/panatta/1fe220.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE220",
    lengthCm: null,
    widthCm: 80,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Iperextension 45 Bench",
    muscle: "Lower Back",
    equipment: "Panatta Machine",
    instructions: "Banco de hiperextensão a 45° para eretores da espinha e fáscia toracolombar.",
    imageUrl: "/machines/panatta/1fe221.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE221",
    lengthCm: null,
    widthCm: 80,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Abdominal Isolator",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Banco isolador de abdominais para reto abdominal. Apoio ajustável. Múltiplas posições.",
    imageUrl: "/machines/panatta/1fe214.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE214",
    lengthCm: 135,
    widthCm: 105,
    heightCm: 170,
    weightKg: 190,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Adjustable Crunch Board",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Prancha ajustável para abdominais. Múltiplas inclinações para variar a intensidade.",
    imageUrl: "/machines/panatta/1fe210.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE210",
    lengthCm: 140,
    widthCm: 75,
    heightCm: 110,
    weightKg: 45,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Sit Up Board",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Prancha para sit-up (abdominais). Apoio de pés ajustável. Inclinação ajustável.",
    imageUrl: "/machines/panatta/1fe212.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE212",
    lengthCm: null,
    widthCm: 80,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Torsion Bench",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Banco de torção para oblíquos e rotação do tronco. Plataforma giratória com apoio de pés.",
    imageUrl: "/machines/panatta/1fe213.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE213",
    lengthCm: null,
    widthCm: 75,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Standing Double Twister",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Twister duplo em pé para oblíquos. Plataforma giratória para rotação do tronco. Com suporte para anilhas.",
    imageUrl: "/machines/panatta/1fe215.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE215",
    lengthCm: null,
    widthCm: 75,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Standing and Seated Double Twister",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Twister duplo em pé e sentado para oblíquos. Permite rotação do tronco em ambas posições. Com suporte para anilhas.",
    imageUrl: "/machines/panatta/1fe216.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE216",
    lengthCm: null,
    widthCm: 105,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Reverse Crunch Abs",
    muscle: "Abs",
    equipment: "Panatta Machine",
    instructions: "Banco para abdominal reverso. Elevação de pelve e pernas para reto abdominal inferior.",
    imageUrl: "/machines/panatta/1fe217.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE217",
    lengthCm: null,
    widthCm: 155,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Sissy Squat",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Sissy squat para quadríceps. Apoio de panturrilha ajustável. Alça de apoio.",
    imageUrl: "/machines/panatta/1fe231a.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE231A",
    lengthCm: null,
    widthCm: 65,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Squat Rack (Fit Evo)",
    muscle: "Quadriceps",
    equipment: "Panatta Machine",
    instructions: "Rack de agachamento. Suportes ajustáveis em altura. Barras de segurança.",
    imageUrl: "/machines/panatta/1fe230.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE230",
    lengthCm: null,
    widthCm: 155,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Smith Machine Linear Bearings",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Smith machine com rolamentos lineares para movimento suave. Trilho guiado. Barras de segurança ajustáveis.",
    imageUrl: "/machines/panatta/1fe113b.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE113B",
    lengthCm: null,
    widthCm: 200,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Stretching Extensor Bench",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Banco de alongamento para extensores. Posições variadas para alongamento de diferentes grupos musculares.",
    imageUrl: "/machines/panatta/1fe260.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE260",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
  {
    name: "Stretching Flexor Bench",
    muscle: "Full Body",
    equipment: "Panatta Machine",
    instructions: "Banco de alongamento para flexores. Posições variadas para alongamento de diferentes grupos musculares.",
    imageUrl: "/machines/panatta/1fe261.png",
    machineBrand: "Panatta",
    machineLine: "Fit Evo",
    machineCode: "1FE261",
    lengthCm: null,
    widthCm: 150,
    heightCm: null,
    weightKg: null,
    maxLoadKg: null,
    isActive: false,
  },
];

async function main() {
  console.log(`Seeding ${panattaMachines.length} Panatta machines...`);

  let created = 0;
  let updated = 0;

  for (const machine of panattaMachines) {
    const existing = await prisma.exercise.findFirst({
      where: { machineCode: machine.machineCode, machineBrand: "Panatta" },
    });

    if (existing) {
      await prisma.exercise.update({
        where: { id: existing.id },
        data: {
          name: machine.name,
          muscle: machine.muscle,
          equipment: machine.equipment,
          instructions: machine.instructions,
          imageUrl: machine.imageUrl,
          machineLine: machine.machineLine,
          machineCode: machine.machineCode,
          lengthCm: machine.lengthCm,
          widthCm: machine.widthCm,
          heightCm: machine.heightCm,
          weightKg: machine.weightKg,
          maxLoadKg: machine.maxLoadKg,
        },
      });
      updated++;
    } else {
      await prisma.exercise.create({
        data: {
          name: machine.name,
          muscle: machine.muscle,
          equipment: machine.equipment,
          instructions: machine.instructions,
          machineBrand: machine.machineBrand,
          machineLine: machine.machineLine,
          machineCode: machine.machineCode,
          lengthCm: machine.lengthCm,
          widthCm: machine.widthCm,
          heightCm: machine.heightCm,
          weightKg: machine.weightKg,
          maxLoadKg: machine.maxLoadKg,
          isCustom: false,
          isActive: machine.isActive,
          gifUrl: null,
          videoUrl: null,
          imageUrl: machine.imageUrl,
        },
      });
      created++;
    }
  }

  console.log(
    `Panatta seed complete: ${created} created, ${updated} updated (${panattaMachines.length} total).`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
